# Generated by Django 4.2.9 on 2024-02-17 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.DeleteModel(
            name="SignUp",
        ),
    ]
