# Generated by Django 5.0.2 on 2024-02-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Fname',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Lname',
            new_name='lName',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.AddField(
            model_name='signup',
            name='password1',
            field=models.CharField(default='password123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='password2',
            field=models.CharField(default='password123', max_length=50),
            preserve_default=False,
        ),
    ]
