# Generated by Django 4.2.9 on 2024-02-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_delete_login_delete_signup"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="group",
            field=models.IntegerField(default=2, max_length=1),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="uploads/accounts/"),
        ),
    ]
