# Generated by Django 4.2.9 on 2024-02-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0010_alter_customer_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="group",
            field=models.OneToOneField(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
