# Generated by Django 4.2.9 on 2024-02-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_customer_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.profile"
            ),
        ),
    ]
